### ISSUE TITLE
Tag v0.0.2

### ISSUE THREAD

**Issue by psyvision** [TypQxQ/Klipper_ToolChanger#2]
Please tag v0.0.2 for plugin installs to pickup recent bug fixes

**Comment by TypQxQ** [comment]
My Mainsail is showing updates as:
`v0.0.1-0 > v0.0.1-4`
Just like all other updates for Example Klipper:
`v0.10.0-318 > v0.10.0-319`

**Comment by psyvision** [comment]
Refreshing now and it does show the changes!  Yesterday I did the update manager and it still showed this as per below:

![image](https://user-images.githubusercontent.com/1932948/159115218-f872fe7b-9bef-41b7-9bdc-ec65a041d452.png)

Cheers
