### ISSUE TITLE
How are the macros supposed to be used?

### ISSUE THREAD

**Issue by viesturz** [TypQxQ/Klipper_ToolChanger#24]
Hi, still trying to get this to work fully.
I noticed that the macros are not installed by default.

What is the plan here? Put all of them into my macros.cfg?
Then why are they each in a separate file? Should I pick and choose? Any recommendations on a good starting set?

**Comment by TypQxQ** [comment]
I use them all but you are right, should add them too.

**Comment by TypQxQ** [comment]
I just updated the documentation. Btw. I like how you started your project.
